### ISSUE TITLE
where is SQLPSX.AllObject.sql

### ISSUE THREAD

**Issue by eliassal** [MikeShepard/SQLPSX#10]
Hi, I downloaded the zip file, in the databse directory there is no file named SQLPSX.AllObject.sql
Thanks for your help

**Comment by MikeShepard** [comment]
I just downloaded the zip and I see it under Modules\SQLServer\Database\sqlpsx.Allobject.sql.

It's also in the same place if you clone the repository.

**Comment by eliassal** [comment]
Thanks, it seems that it was a download issue
