### ISSUE TITLE
BulkCopy typo

### ISSUE THREAD

**Issue by DumbRadish** [MikeShepard/SQLPSX#26]
On line 697 of the adoLib file there is a typo where it says "elsif" instead of "elseif". Thanks.

**Comment by MikeShepard** [comment]
I'm not seeing this.  Looking at the file (changed 3 years ago), here's the end of the file (from 694 on):

    } elseif ($records -is [System.Data.Common.DbDataReader]){
		#if passed a Datareader object use it to stream the records
		$bulkCopy.WriteToServer($records)
	} else {
		$bulkCopy.WriteToServer($records)
	}
	write-debug "Bulk copy finished at $(get-date)"
}

**Comment by MikeShepard** [comment]
Looks like the last commit (in august of 2015) fixed this typo.

**Comment by DumbRadish** [comment]
I am (perhaps mistakenly) running the SQLPSX.msi installer file in the Deprecated/SQLPSXInstaller folder. This creates a file in the adoLib folder called adoLib.psm1 (with a date modified of 09/03/2011). Those last few lines look like this:

```
} elsif ($records -is [System.Data.Common.DbDataReader]){
		#if passed a Datareader object use it to stream the records
		$bulkCopy.WriteToServer($records)
	} else {
		$bulkCopy.WriteToServer($records)
	}
	write-debug "Bulk copy finished at $(get-date)"

```

**Comment by MikeShepard** [comment]
I wouldn't recommend using anything in the Deprecated folder.  The dates on
the files in github show "2 years ago", but the files in it are dated from
when I copied the project from Codeplex.  As you can see on adolib, it's 7
years old, and 4 years older than the latest commit on the actual
(non-deprecated) file.
